config/routes.rb
Rails.application.routes.draw do
  # home
  root 'static_pages#home'
  get  '/help', to:'static_pages#help'
  get  '/about', to:'static_pages#about'
  # user
  # signup
  get  '/send_activation_email', to:'users#enter_activaton_email'
  post '/send_activation_email', to:'users#send_activaton_email'
  get  '/authenticate_authcode', to:'users#enter_authcode'
  post '/authenticate_authcode', to:'users#authenticate_authcode'
  get  '/signup', to:'users#new'
  post '/signup',  to:'users#create'
  get  '/confirm', to:'users#confirm'
  post '/confirm', to:'users#confirm'
  # login
  get  '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete  '/logout', to:'sessions#destroy'
  # users_edit
  get 'users/:id/edit_user_prof', to:'users#edit_prof'
  patch '/users/:id/edit_user_prof', to:'users#update_prof'
  get 'users/:id/edit_user_account', to:'users#edit_account'
  get 'users/:id/edit_user_password', to:'users#edit_password'
  patch 'users/:id/edit_user_password', to:'users#update_password'
  get 'users/:id/withdraw', to:'users#withdraw'
  get 'announce_send_password', to:'password_resets#announce_send_password'
  get 'announce_success_change_password', to:'password_resets#announce_success_change_password'
  get 'email_resets/:id/new', to:'email_resets#new'
  post 'email_resets/:id/create', to:'email_resets#create'
  post '/email_resets/:id/update', to:'email_resets#update'
  # movie
  get 'movies/list', to:'movies#list'
  get 'movies/list/now', to:'movies#now'
  get 'movies/list/rental_coming', to:'movies#rental_coming'
  get 'movies/list/rental_now', to:'movies#rental_now'
  # get 'movies/list/recommended', to:'movies#recommended'
  get 'movies/list/year/:year', to:'movies#year' 
  get 'movies/list/genre/:genre', to:'movies#genre' 
  get 'movies/list/production/:production', to:'movies#production' 
  # drama
  get 'dramas/list', to:'dramas#list'
  get 'dramas/list/now', to:'dramas#now'
  get 'dramas/list/rental_coming', to:'dramas#rental_coming'
  get 'dramas/list/rental_now', to:'dramas#rental_now'
  #get 'dramas/list/recommended', to:'dramas#recommended'
  get 'dramas/list/year/:year', to:'dramas#year' 
  get 'dramas/list/genre/:genre', to:'dramas#genre' 
  get 'dramas/list/production/:production', to:'dramas#production' 
  # cast
  get 'casts/drama/:id', to:'casts#show_drama'
  resources :users do
    member do
      get :following, :followers, :show_review_drama, :show_book_movie, :show_book_drama
    end
  end
  resources :movies, :dramas do
    resources :reviews,           only: [:new, :create, :edit, :update]
    resources :books,             only: [:create, :destroy]
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :email_resets,        only: [:edit]
  resources :movies,              only: [:show]
  resources :dramas,              only: [:show]
  resources :casts,               only: [:show] do
    resources :likes,             only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :year_cut, only:[:year]
  before_action :genre_translate, only:[:genre]
  before_action :production_translate, only:[:production]
  
  def now
    @movies = Movie.where(status: "公開中").page(params[:page]).per(10)
    #Movie.where(status: "公開中") ← Movieモデルからstatusが"公開中"のレコードを抽出
    #page(params[:page]).per(10) ← ページパラメータを取得(10件毎)
  end
  
  def rental_coming
    @movies = Movie.where(status: "レンタル予定").page(params[:page]).per(10)
  end
  
  def rental_now
    @movies = Movie.where(status: "レンタル").page(params[:page]).per(10)
  end
  
  def show
    @movie = Movie.find(params[:id])
    @reviews = Review.where(movie_id: @movie.id).page(params[:page]).per(10)
    if logged_in?
      @review = get_current_user_review
    end
    @average_star = get_average_star
  end
  
  def year
    if @year.to_i > 2000
      @movies = Movie.where(release: "#{@year}/01/01".."#{@year}/12/31").page(params[:page]).per(10)
    else
      @movies = Movie.where(release: "#{@year}/01/01".."#{@year.to_i + 9}/12/31").page(params[:page]).per(10)
    end
  end
  
  def genre
    @movies = Movie.where(genre: @genre_translated).page(params[:page]).per(10)
  end
  
  def production
    @movies = Movie.where(production: @production_translated).page(params[:page]).per(10)
  end
  
  private
    def year_cut
      @year = params[:year]
      year = @year.to_i
      if(year >= 2020)
        @year = "2019"
      elsif(year >= 2010)
      elsif(year >= 2000)
        @year = "2000"
      elsif(year >= 1990)
        @year = "1990"
      elsif(year >= 1980)
        @year = "1980"
      else
        @year = "1970"
      end
    end
    
    def genre_translate
      @genre = params[:genre]
      case @genre
      when "suspense" then
        @genre_translated = "サスペンス"
      when "documentary" then
        @genre_translated = "ドキュメンタリー"
      when "action" then
        @genre_translated = "アクション"
      when "SF" then
        @genre_translated = "SF"
      when "comedy" then
        @genre_translated = "コメディ"
      when "horror" then
        @genre_translated = "ホラー"
      end
    end
    
    def production_translate
      @production = params[:production]
      case @production
      when "america" then
        @production_translated = "アメリカ"
      when "england" then
        @production_translated = "イギリス"
      when "spain" then
        @production_translated = "スペイン"
      when "syria" then
        @production_translated = "シリア"
      when "canada" then
        @production_translated = "カナダ"
      when "france" then
        @production_translated = "フランス"
      else
        @production_translated = "アメリカ"
      end
    end
    
    def get_current_user_review
      @reviews.empty? ? nil: @reviews.find_by(user_id: current_user.id)
    end
    
    def get_average_star
      ave_star = @reviews.empty? ? 0: @reviews.average(:star).to_f
      if ave_star >= 4.5
        4.5
      elsif ave_star >= 4.0
        4.0
      elsif ave_star >= 3.5
        3.5
      elsif ave_star >= 3.0
        3.0
      elsif ave_star >= 2.5
        2.5
      elsif ave_star >= 2.0
        2.0
      elsif ave_star >= 1.5
        1.5
      elsif ave_star >= 1.0
        1.0
      elsif ave_star >= 0.5
        0.5
      else
        0
      end
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/genre.html.erb
<% provide(:title, "#{@genre_translated}のおすすめ映画作品")%>
<%=render("shared/movie_genre_sidebar.html.erb")%>
<%=render("shared/movie_information.html.erb")%>

app/views/movies/now.html.erb
<% provide(:title, "上映中の映画")%>
<%=render("shared/movie_list_sidebar.html.erb")%>
<%=render("shared/movie_information.html")%>

app/views/movies/production.html.erb
<% provide(:title, "#{@production_translated}のおすすめ映画作品")%>
<%=render("shared/movie_production_sidebar.html.erb")%>
<%=render("shared/movie_information.html.erb")%>

app/views/movies/rental_coming.html.erb
<% provide(:title, "レンタル開始予定の映画")%>
<%=render("shared/movie_list_sidebar.html.erb")%>
<%=render("shared/movie_information.html")%>

app/views/movies/rental_now.html.erb
<% provide(:title, "レンタル")%>
<%=render("shared/movie_list_sidebar.html.erb")%>
<%=render("shared/movie_information.html")%>

  

app/views/movies/show.html.erb
<% provide(:title, "#{@movie.title}-映画情報・レビュー・評価")%>
<div class="row mt-3">
  <div class="col-md-3 movie_image">
    <% if @movie.picture.nil?%>
      <%= image_tag 'no_image.jpg', size: "260x364" %>
    <%else%>
      <%= image_tag @movie.picture, size: "260x364"%>
    <% end %>
    <div class="btn-group mt-2 review_btns_show" role="group" aria-label="Basic example">
      <% if logged_in?%>
        <% unless @review.nil? %>
          <%= link_to edit_movie_review_path(@movie, @review), class: "btn btn-outline-light pl-5 pr-5 btn-on" do %>
            <i class="far fa-eye fa-2x"></i> <br>
            <%= @reviews.count %>
          <% end %>
        <% else %>
          <%= link_to new_movie_review_path(@movie), class: "btn btn-outline-light pl-5 pr-5 btn-off" do %>
            <i class="far fa-eye fa-2x"></i> <br>
            <%= @reviews.count %>
          <% end %>
        <% end %>
        <% if Book.find_by(user_id: current_user.id, movie_id: @movie.id) %>
          <%= link_to movie_book_path(@movie), method: :delete,class: "btn btn-outline-light pl-5 pr-5 btn-on", remote: true do%>
            <i class="fas fa-layer-group fa-2x"></i> <br>
            <%= @movie.books.count%>
          <% end %>
        <% else %>
          <%= link_to movie_books_path(@movie), method: :post,class: "btn btn-outline-light pl-5 pr-5 btn-off", remote: true do%>
            <i class="fas fa-layer-group fa-2x"></i> <br>
            <%= @movie.books.count%>
          <% end %>
        <% end %>
      <% end %>
    </div> 
  </div>
  <div class="col-md-9 movie_show_text">
    <h5 class="font-weight-bold"><%=@movie.title%>　
    <span class="small font-weight-bold">（<%= link_to "#{@movie.release.year}年", "/movies/list/year/#{@movie.release.year}" %>製作の映画）</span></h5>
    <p>
      <span class="font-weight-bold">上映日：</span><%= "#{@movie.release.year}年#{@movie.release.mon}月#{@movie.release.day}日"%> ／
      <span class="font-weigsht-bold">製作国：</span><%= link_to @movie.production, "/movies/list/production/#{@movie.production_translation}"%> ／
      <span class="font-weight-bold">上映時間：</span><%= "#{@movie.screening_time}分"%> 
    </p>
    <p>
      <span class="font-weight-bold">ジャンル：</span><%= link_to @movie.genre, "/movies/list/genre/#{@movie.genre_translation}"%>
    </p>
    <p class="star">
      <span id="star-rate-<%= @movie.id %>"></span>
      <script>
        $('#star-rate-<%= @movie.id %>').raty({
          size: 100,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= @average_star %>,
        });
      </script> 
      <span class="star-text">
        <% if @average_star != 0 %>
          <%= @average_star %> 
        <% else %>
          <span class="small">評価はまだありません</span>
        <% end %>
      </span>
    </p>
    <div class="row">
      <div class="col-md-auto">
        <p class="mt-2"><span class="font-weight-bold">監督</span></p>
        <% director_ids = @movie.movie_casts.where(relation: "director").select(:cast_id)%>
        <% Cast.where(id: director_ids).each do |director| %>
          <%= link_to director.name, director, class: "btn btn-light btn-sm cast_name mt-1" %>
        <% end %>
      </div>
      <div class="col-md-auto">
        <p class="mt-2"><span class="font-weight-bold">脚本</span></p>
        <% writer_ids = @movie.movie_casts.where(relation: "writer").select(:cast_id)%>
        <% Cast.where(id: writer_ids).each do |writer| %>
          <%= link_to writer.name, writer, class: "btn btn-light btn-sm cast_name mt-1" %>
        <% end %>
      </div>
    </div>
    <p class="mt-3"><span class="font-weight-bold">出演者</span></p>
    <% actor_ids = @movie.movie_casts.where(relation: "actor").select(:cast_id)%>
    <% actor_ids.each do |actor_id| %>
      <% actor = Cast.find(actor_id.cast_id) %>
      <%= link_to actor.name, actor, class: "btn btn-light btn-sm cast_name mt-2 mr-1" %>
    <% end %>
  </div>
</div>
<div class="col-md-8　mx-auto">
  <div class="card card_top">
    <div class="card-header text-secondary"><%="「#{@movie.title}」に投稿された感想・評価" %></div>
    <div class="card-body movie_list">
      <%=render @reviews %>
      <%= paginate @reviews, theme: 'twitter-bootstrap-4'%>
    </div>
  </div>
</div>

app/views/movies/year.html.erb
<% if @year.to_i > 2000%>
  <% provide(:title, "#{@year}年製作のおすすめ映画作品")%>
<% else %>
  <% provide(:title, "#{@year}年代製作のおすすめ映画作品")%>
<% end %>
<%=render("shared/movie_year_sidebar.html.erb")%>
<%=render("shared/movie_information.html.erb")%>