config/routes.rb
Rails.application.routes.draw do
  # home
  root 'static_pages#home'
  get  '/help', to:'static_pages#help'
  get  '/about', to:'static_pages#about'
  # user
  # signup
  get  '/send_activation_email', to:'users#enter_activaton_email'
  post '/send_activation_email', to:'users#send_activaton_email'
  get  '/authenticate_authcode', to:'users#enter_authcode'
  post '/authenticate_authcode', to:'users#authenticate_authcode'
  get  '/signup', to:'users#new'
  post '/signup',  to:'users#create'
  get  '/confirm', to:'users#confirm'
  post '/confirm', to:'users#confirm'
  # login
  get  '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete  '/logout', to:'sessions#destroy'
  # users_edit
  get 'users/:id/edit_user_prof', to:'users#edit_prof'
  patch '/users/:id/edit_user_prof', to:'users#update_prof'
  get 'users/:id/edit_user_account', to:'users#edit_account'
  get 'users/:id/edit_user_password', to:'users#edit_password'
  patch 'users/:id/edit_user_password', to:'users#update_password'
  get 'users/:id/withdraw', to:'users#withdraw'
  get 'announce_send_password', to:'password_resets#announce_send_password'
  get 'announce_success_change_password', to:'password_resets#announce_success_change_password'
  get 'email_resets/:id/new', to:'email_resets#new'
  post 'email_resets/:id/create', to:'email_resets#create'
  post '/email_resets/:id/update', to:'email_resets#update'
  # movie
  get 'movies/list', to:'movies#list'
  get 'movies/list/now', to:'movies#now'
  get 'movies/list/rental_coming', to:'movies#rental_coming'
  get 'movies/list/rental_now', to:'movies#rental_now'
  # get 'movies/list/recommended', to:'movies#recommended'
  get 'movies/list/year/:year', to:'movies#year' 
  get 'movies/list/genre/:genre', to:'movies#genre' 
  get 'movies/list/production/:production', to:'movies#production' 
  # drama
  get 'dramas/list', to:'dramas#list'
  get 'dramas/list/now', to:'dramas#now'
  get 'dramas/list/rental_coming', to:'dramas#rental_coming'
  get 'dramas/list/rental_now', to:'dramas#rental_now'
  #get 'dramas/list/recommended', to:'dramas#recommended'
  get 'dramas/list/year/:year', to:'dramas#year' 
  get 'dramas/list/genre/:genre', to:'dramas#genre' 
  get 'dramas/list/production/:production', to:'dramas#production' 
  # cast
  get 'casts/drama/:id', to:'casts#show_drama'
  resources :users do
    member do
      get :following, :followers, :show_review_drama, :show_book_movie, :show_book_drama
    end
  end
  resources :movies, :dramas do
    resources :reviews,           only: [:new, :create, :edit, :update]
    resources :books,             only: [:create, :destroy]
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :email_resets,        only: [:edit]
  resources :movies,              only: [:show]
  resources :dramas,              only: [:show]
  resources :casts,               only: [:show] do
    resources :likes,             only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  has_many :reviews,dependent: :destroy
    has_many :movies, through: :reviews
    has_many :dramas, through: :reviews
  has_many :books,dependent: :destroy
    has_many :movies, through: :books
    has_many :dramas, through: :books
  has_many :likes,dependent: :destroy
    has_many :casts, through: :likes
  has_many :active_relationships, class_name:  "Relationship",
    foreign_key: "follower_id",
    dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
    foreign_key: "followed_id",
    dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  before_save :downcase_email
  #before_create :create_activation_digest
  validates :name, presence:true, length:{maximum:15},
                   uniqueness:true, on: :change_name
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:true, length:{maximum:255},
                    format:{with:VALID_EMAIL_REGEX},
                    uniqueness:{case_sensitive:false}, on: :change_email
  has_secure_password
  VALID_PASSWORD_REGEX = /\A\w+$\z/i
  validates :password, presence:true, length:{minimum:5},
                       format:{with:VALID_PASSWORD_REGEX}, on: :change_password
  validates :nickname, presence:true, length:{maximum:15}, on: :change_nickname
  validates_acceptance_of :agreement, :acceptance =>true, on: :change_agreement
  validates_acceptance_of :activated, :acceptance =>true, on: :change_activated
  validates :profile, length:{maximum:1200}, on: :change_profile
  
  
  # 渡された文字列のハッシュ値を返す
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  #ランダムなトークンを返す
  def self.new_token
    SecureRandom.urlsafe_base64
  end
  
  #永続セッションの為、ユーザーをデータベースに登録する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # トークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil? or digest.empty?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  #ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  #アクティベーショントークンを生成する
  def create_activation_digest
    self.activation_token = sprintf("%.4d", rand(10000))
    self.activation_digest = User.digest(activation_token)
  end
  
  #リセットトークンを生成する
  def create_reset_digest(token)
    if token == "password"
      self.reset_token = SecureRandom.urlsafe_base64
    else
      self.reset_token = sprintf("%.4d", rand(10000))
    end
    update_columns(reset_digest:  User.digest(reset_token), reset_sent_at: Time.zone.now)
  end
  
  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  #  Email再設定のメールを送信する
  def send_email_reset_email
    UserMailer.email_reset(self).deliver_now
  end
  
  # パスワード再設定の期限が切れている場合はtrueを返す
  def reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end
  
  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
  
  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
  
  private
    # メールアドレスをすべて小文字にする
    def downcase_email
      self.email.downcase!
    end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery
  before_action :logged_in_user, only:[:edit_prof,:update_prof,:edit_account,
                                       :edit_email,:edit_password,:update_password, :destroy]
  before_action :correct_user, only:[:edit_prof,:update_prof,:edit_account,:edit_email,:edit_password,:update_password, ]
  before_action :admin_user, only:[:destroy]
  before_action :not_post_for_confirm, only:[:confirm]
  before_action :set_user, only:[:show, :edit_prof, :update_prof, :edit_account, :edit_password, :update_password, :withdraw,
                                :show_review_drama, :show_book_movie, :show_book_drama]
  
  def new
    @user = User.new
    @user.email = params[:email]
    @user.activation_digest = params[:activation_digest]
    @user.activated_at = params[:activated_at]
    @user.activated = params[:activated]
    activated_user
  end
  
  def show
    @reviews = @user.reviews.where.not(movie_id: nil).page(params[:page]).per(6)
  end
  
  def enter_activaton_email
    @user = User.new
  end
  
  def send_activaton_email
    @user = User.new(user_params)
    @user.password = "password"
    if @user.valid?(:change_email)
      @user.password = nil
      @user.create_activation_digest
      UserMailer.account_activation(@user).deliver_now
      redirect_to action: 'enter_authcode', email: @user.email, activation_digest: @user.activation_digest
    else
      @user.password = nil
      render 'enter_activaton_email'
    end
  end
  
  def enter_authcode
    @user = User.new(email: params[:email])
    @user.activation_digest = params[:activation_digest]
  end
  
  def authenticate_authcode
    @user = User.new(email: params[:email])
    @user.activation_digest = params[:activation_digest]
    if @user.authenticated?(:activation, params[:authenticate][:authcode])
      @user.activated = true
      @user.activated_at = Time.zone.now
      redirect_to action: 'new', email: @user.email, activation_digest: @user.activation_digest, 
                                 activated_at: @user.activated_at, activated: @user.activated
    else
      flash.now[:danger] = "認証番号が間違っているか、認証期間が無効です"
      render 'enter_authcode'
    end
  end
  
  def confirm
    @user = User.new(user_params)
    render 'new' if @user.invalid?([:change_name, :change_password, :change_nickname, 
                                      :change_agreement, :change_activated, :change_email])
  end

  def create
    @user = User.new(user_params)
    if params[:back]
      render 'new'
    elsif @user.save(context: [:change_name, :change_password, :change_nickname, 
                    :change_agreement, :change_activated, :change_email])
      log_in(@user)
      flash[:success] = "ユーザー登録が完了しました"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit_prof
  end
  
  def update_prof
    @user.assign_attributes(user_params)
    if @user.save(context: [:change_nickname, :change_profile])
      flash[:success] = "設定を保存しました"
      redirect_to action: 'edit_prof'
    else
      render :edit_prof
    end
  end
  
  def edit_account
  end
  
  def edit_password
  end
  
  def update_password
    @user.assign_attributes(user_params)
    if  @user.save(context: :change_password)
      flash[:success] = "パスワード変更が完了しました"
      redirect_to action: 'edit_password'
    else
      flash.now[:danger] = "パスワードが変更できませんでした"
      render 'edit_password'
    end
  end
  
  def withdraw
  end
  
  def index
    @users = User.all
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "退会が完了しました"
    redirect_to root_url
  end
  
  def following
    @title = "フォロー"
    @user  = User.find(params[:id])
    @users = @user.following.page(params[:page]).per(10)
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user  = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(10)
    render 'show_follow'
  end
  
  def show_review_drama
    @reviews = @user.reviews.where.not(drama_id: nil).page(params[:page]).per(6)
  end
  
  def show_book_movie
    @books = @user.books.where.not(movie_id: nil).page(params[:page]).per(6)
  end
  
  def show_book_drama
    @books = @user.books.where.not(drama_id: nil).page(params[:page]).per(6)
  end
  
  
  private
    def set_user
      @user = User.find(params[:id])
    end
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :nickname, 
                                   :agreement, :profile, :activated, :activated_at, :activation_digest)
    end
    
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user)
    end
    
    def admin_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user.admin? || current_user?(@user)
    end
    
    def activated_user
      redirect_to send_activation_email_path unless @user.activated
    end
    
    def not_post_for_confirm
      unless request.post?
        flash[:danger] = "会員登録に失敗しました。もう一度会員登録をしてください。"
        redirect_to(root_url) 
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, size=100)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt:user.name, class:"gravatar")
  end
end

app/views/users/_book_show_drama.html.erb
  <div class="col-md-6">
    <div class="card mb-4">
      <div class="card-body">
        <div class="row">
          <div class="col-md-6">
            <p class="font-weight-bold"><%= "#{book.drama.title} (#{book.drama.release.year}年制作の映画)" %></p>
            <p class="star">
              <span id="star-rate-<%= book.id %>"></span>
            <div class="d-block mt-2">
              <%= link_to ">>詳しい情報を見る", book.drama, class:"float-right cast_name"%>
            </div>
          </div>
          <div class="col-md-6 movie_image">
            <% if book.drama.picture.nil?%>
              <%= image_tag 'no_image.jpg', size: "150x200" %>
            <%else%>
              <%= image_tag book.drama.picture, size: "150x200"%>
            <% end %>
            <div class="btn-group mt-2 review_btns_show_3" role="group" aria-label="Basic example">
            <% if logged_in? %>
              <% if Book.find_by(user_id: current_user.id, drama_id: book.drama.id) %>
                <%= link_to drama_book_path(book.drama), method: :delete,class: "btn btn-outline-light btn-small btn-on", remote: true do%>
                  <i class="fas fa-layer-group fa-2x"></i> <br>
                  <%= book.drama.books.count%>
                <% end %>
              <% else %>
                <%= link_to drama_books_path(book.drama), method: :post,class: "btn btn-outline-light btn-small btn-off", remote: true do%>
                  <i class="fas fa-layer-group fa-2x"></i> <br>
                  <%= book.drama.books.count%>
                <% end %>
              <% end %>
            <% end %>
            </div>
          </div>
        </div>  
      </div>
    </div>
  </div>

app/views/users/_book_show_movie.html.erb
  <div class="col-md-6">
    <div class="card mb-4">
      <div class="card-body">
        <div class="row">
          <div class="col-md-6">
            <p class="font-weight-bold"><%= "#{book.movie.title} (#{book.movie.release.year}年制作の映画)" %></p>
            <p class="star">
              <span id="star-rate-<%= book.id %>"></span>
            <div class="d-block mt-2">
              <%= link_to ">>詳しい情報を見る", book.movie, class:"float-right cast_name"%>
            </div>
          </div>
          <div class="col-md-6 movie_image">
            <% if book.movie.picture.nil?%>
              <%= image_tag 'no_image.jpg', size: "150x200" %>
            <%else%>
              <%= image_tag book.movie.picture, size: "150x200"%>
            <% end %>
            <div class="btn-group mt-2 review_btns_show_3" role="group" aria-label="Basic example">
            <% if logged_in? %>
              <% if Book.find_by(user_id: current_user.id, movie_id: book.movie.id) %>
                <%= link_to movie_book_path(book.movie), method: :delete,class: "btn btn-outline-light btn-small btn-on", remote: true do%>
                  <i class="fas fa-layer-group fa-2x"></i> <br>
                  <%= book.movie.books.count%>
                <% end %>
              <% else %>
                <%= link_to movie_books_path(book.movie), method: :post,class: "btn btn-outline-light btn-small btn-off", remote: true do%>
                  <i class="fas fa-layer-group fa-2x"></i> <br>
                  <%= book.movie.books.count%>
                <% end %>
              <% end %>
            <% end %>
            </div>
          </div>
        </div>  
      </div>
    </div>
  </div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= button_tag :type => "submit", :class =>"btn btn-light" do %>
    <i class="fas fa-user-plus"></i>フォロー
  <% end %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(user) %>
  <div id="follow_form">
  <% if current_user.following?(user) %>
    <%= render partial:'unfollow', locals: {user: user} %>
  <% else %>
    <%= render partial:'follow', locals: {user: user} %>
  <% end %>
  </div>
<% end %>

app/views/users/_show_profile.html.erb
<div class="row">
  <div class="col-md-auto profile-image">
    <%= gravatar_for @user %>
  </div>
  <div class="col-md-auto profile-text">
    <h2>
      <%= @user.nickname%>
      <span><%= "@" + @user.name %></span>
    </h2>
    <small>
      <%= simple_format(@user.profile) %>
    </small>
  </div>
  <div class="col-md float-right ">
    <% if current_user?(@user) %>
      <%= link_to "プロフィール編集", "/users/#{@user.id}/edit_user_prof", class: "btn btn-secondary profile_edit_btn" %>
    <% else %>
      <div class="mt-3">
        <%= render partial:'follow_form', locals:{user: @user} if logged_in? %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/confirm.html.erb
<% provide(:title, "メンバー登録（確認）")%>
<div class="row justify-content-center">
  <div class="col-md-8">
    <div class="card card_top">
      <div class="card-header">メンバー登録（確認）</div>
      <div class="card-body">
        <%= form_for(@user, url:signup_path,html: { class: "form-horizontal" }) do |f| %>
          <%= f.hidden_field :name %>
          <%= f.hidden_field :email %>
          <%= f.hidden_field :password %>
          <%= f.hidden_field :password_confirmation %>
          <%= f.hidden_field :nickname %>
          <%= f.hidden_field :agreement %>
          <%= f.hidden_field :activation_digest%>
          <%= f.hidden_field :activated_at%>
          <%= f.hidden_field :activated%>
          <div class="cols-sm-10 confirm-text">
            <h5 class="strong">Kamarks ID（15文字以内）</h5>
            <p class="small">登録後に変更はできません</p>
            <h4><%= @user.name %></h>
          </div>
          <div class="cols-sm-10 confirm-text">
            <h5 class="strong">パスワード（半角英数字5文字以上）</h5>
            <h4 class="password_confirm">●●●●●</h4>
          </div>
          <div class="cols-sm-10 confirm-text">
            <h5 class="strong">ニックネーム（15文字以内）</h5>
            <p class="small">後で変更することも可能です</p>
            <h4><%= @user.nickname %></h>
          </div>
          <div class="cols-sm-10">
            <div class="form-group ">
              <%= f.submit '入力内容を編集し直す', name: 'back', class: "btn btn-secondary btn-lg btn-block"%>
            </div>
          </div>
          <div class="cols-sm-10">
            <div class="form-group ">
              <%= f.submit '登録する', class: "btn btn-success btn-lg btn-block" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit_email.html.erb
<% provide(:title, "メール設定")%>
<%=render("shared/edit_user_sidebar.html.erb")%>
  <div class="col-md-8">
    <div class="card card_top">
      <div class="card-body">
        <%= form_for(@user, url:"#",html: { class: "form-horizontal" }) do |f| %>
          <%= render 'shared/error_messages' %>
          <div class="cols-sm-10">
            <h5 class="strong">メールアドレスを変更する</h5>
            <p class="small text-secondary">変更するメールアドレスを入力してください。<br>入力したメールアドレス宛にメールを送信します。</p>
          </div>
          <div class="form-group">
            <%= f.label :email,"メールアドレス（必須）", class: "cols-sm-2 control-label" %>
            <div class="cols-sm-10">
              <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                <%= f.text_field :email , class: "form-control", placeholder: "example@example.com", type: "email" %>
              </div>
            </div>
          </div>
          <div class="cols-sm-10">
            <div class="form-group ">
              <%= f.submit 'メール変更', class: "btn btn-success" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit_password.html.erb
<% provide(:title, "パスワード設定")%>
<%=render("shared/edit_user_sidebar.html.erb")%>
<div class="col-md-8">
    <div class="card card_top">
      <div class="card-body">
        <%= form_for(@user, url:"/users/#{@user.id}/edit_user_password",html: { class: "form-horizontal" }) do |f| %>
          <%= render 'shared/error_messages' %>
          <div class="form-group">
              <%= f.label :password, "新しいパスワード（半角英数字5文字以上）", class: "cols-sm-2 control-label"  %>
              <div class="cols-sm-10">
                <div class="input-group">
                  <%= f.text_field :password , class: "form-control", placeholder: "パスワードを入力してください", type: "password" %>
                </div>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :password_confirmation, "新しいパスワード確認", class: "cols-sm-2 control-label"  %>
              <div class="cols-sm-10">
                <div class="input-group">
                  <%= f.text_field :password_confirmation , class: "form-control", placeholder: "パスワードを入力してください", type: "password"%>
                </div>
              </div>
            </div>
          <div class="cols-sm-10">
            <div class="form-group ">
              <%= f.submit '変更内容を保存する', class: "btn btn-success" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/enter_authcode.html.erb
<% provide(:title, "メンバー登録")%>
<div class="row justify-content-center">
  <div class="col-md-8">
    <div class="card card_top">
      <div class="card-header">メンバー登録（認証番号確認）</div>
      <div class="card-body mb-5 mt-4">
        <%= form_for(:authenticate, url:authenticate_authcode_path,html: { class: "form-horizontal" }) do |f| %>
          <%= hidden_field_tag :email, @user.email %>
          <%= hidden_field_tag :activation_digest, @user.activation_digest %>
          <div class="form-group" style="margin-top:3em;">
            <%= f.label :authcode, "認証番号", class: "cols-sm-2 control-label"  %>
            <div class="cols-sm-10">
              <div class="input-group">
                <%= f.text_field :authcode , class: "form-control", placeholder: "メールに記載されている認証番号を入力してください" %>
              </div>
            </div>
          </div>
          <% if flash.empty?%>
            <div class="form-group" style="margin-top:5em;">
              <%= f.submit "会員登録をする", class: "btn btn-success btn-lg btn-block login-button mb-5" %>
            </div>
          <% else %>
            <div class="row">
              <div class="form-group col-md-6" style="margin-top:3em;">
                <%= link_to "メンバー登録のトップに戻る", send_activation_email_path , class: "btn btn-secondary btn-lg btn-block login-button" %>
              </div>
              <div class="form-group col-md-6" style="margin-top:3em;">
                <%= f.submit "会員登録をする", class: "btn btn-success btn-lg btn-block login-button" %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, "ユーザーを探す"%>
<div class="card card_top">
  <div class="card-header text-center font-weight-bold">人気ユーザー５０人</div>
</div>
<div class="card card_top">
  <div class="card-body">
    <% @users.each_slice(2) do |left_user, right_user| %>
      <div class="row">
        <%= render partial: 'shared/user_index', locals: { user: left_user } %>
        <% unless right_user.nil?%>
          <%= render partial: 'shared/user_index', locals: { user: right_user } %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "#{@user.nickname}さんの映画レビュー")%>
<%= render 'show_profile'%>
<div class="d-flex justify-content-center mt-5 mb-4">
  <div class="btn-group" role="group" aria-label="Basic example">
    <%= link_to "映画", @user, class: "btn btn-dark pl-4 pr-4" %>
    <%= link_to "ドラマ", show_review_drama_user_path(@user), class: "btn btn-secondary pl-3 pr-3" %>
  </div>
</div>
<div class="d-flex justify-content-center mt-5 mb-4">
  <div class="btn-group" role="group" aria-label="Basic example">
    <%= link_to @user, class: "btn btn-secondary pl-5 pr-5" do%>
      <i class="far fa-eye"></i> <br>
      <%= @user.reviews.where.not(movie_id: nil).count %>
    <% end %>
    <%= link_to show_book_movie_user_path(@user), class: "btn btn-outline-secondary pl-5 pr-5" do%>
      <i class="fas fa-layer-group"></i> <br>
      <%= @user.books.count %>
    <% end %>
    <%= link_to "#", class: "btn btn-outline-secondary pl-5 pr-5" do%>
      <i class="far fa-heart"></i> <br>
      <%= "0" %>
    <% end %>
    <%= link_to followers_user_path(@user), class: "btn btn-outline-secondary pl-3 pr-3" do%>
      followers <br>
      <%= @user.followers.count %>
    <% end %>
    <%= link_to following_user_path(@user), class: "btn btn-outline-secondary pl-3 pr-3" do%>
      following <br>
      <%=@user.following.count %>
    <% end %>
  </div>
</div>
<div class="card card_top">
  <div class="card-body">
    <% @reviews.each_slice(2) do |left_review, right_review| %>
      <div class="row">
        <%= render partial: 'review_show_movie.html.erb', locals: { review: left_review } %>
        <% unless right_review.nil?%>
          <%= render partial: 'review_show_movie.html.erb', locals: { review: right_review } %>
        <% end %>
      </div>
    <% end %>
    <%= paginate @reviews, theme: 'twitter-bootstrap-4'%>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, "#{@user.nickname}さんの#{@title}")%>
<%= render 'show_profile'%>
<div class="d-flex justify-content-center mt-5 mb-4">
  <div class="btn-group" role="group" aria-label="Basic example">
    <%= link_to @user, class: "btn btn-outline-secondary pl-5 pr-5" do%>
      <i class="far fa-eye"></i> <br>
      <%= @user.reviews.count %>
    <% end %>
    <%= link_to "#", class: "btn btn-outline-secondary pl-5 pr-5" do%>
      <i class="fas fa-layer-group"></i> <br>
      <%= "0" %>
    <% end %>
    <%= link_to "#", class: "btn btn-outline-secondary pl-5 pr-5" do%>
      <i class="far fa-heart"></i> <br>
      <%= "0" %>
    <% end %>
    <% if @title == "フォロワー"%>
      <%= link_to followers_user_path(@user), class: "btn btn-secondary pl-3 pr-3" do%>
        followers <br>
        <%= @user.followers.count %>
      <% end %>
      <%= link_to following_user_path(@user), class: "btn btn-outline-secondary pl-3 pr-3" do%>
        following <br>
        <%=@user.following.count %>
      <% end %>
    <% else %>
      <%= link_to followers_user_path(@user), class: "btn btn-outline-secondary pl-3 pr-3" do%>
        followers <br>
        <%= @user.followers.count %>
      <% end %>
      <%= link_to following_user_path(@user), class: "btn btn-secondary pl-3 pr-3" do%>
        following <br>
        <%=@user.following.count %>
      <% end %>
    <% end %>
  </div>
</div>
<section class="stats">
  <% if @users.any? %>
    <div class="card card_top">
      <div class="card-body">
        <% @users.each_slice(2) do |left_user, right_user| %>
          <div class="row">
            <%= render partial: 'shared/user_index', locals: { user: left_user } %>
            <% unless right_user.nil?%>
              <%= render partial: 'shared/user_index', locals: { user: right_user } %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <%= paginate @users, theme: 'twitter-bootstrap-4'%>
  <% end %>
</section>