config/routes.rb
Rails.application.routes.draw do
  # home
  root 'static_pages#home'
  get  '/help', to:'static_pages#help'
  get  '/about', to:'static_pages#about'
  # user
  # signup
  get  '/send_activation_email', to:'users#enter_activaton_email'
  post '/send_activation_email', to:'users#send_activaton_email'
  get  '/authenticate_authcode', to:'users#enter_authcode'
  post '/authenticate_authcode', to:'users#authenticate_authcode'
  get  '/signup', to:'users#new'
  post '/signup',  to:'users#create'
  get  '/confirm', to:'users#confirm'
  post '/confirm', to:'users#confirm'
  # login
  get  '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete  '/logout', to:'sessions#destroy'
  # users_edit
  get 'users/:id/edit_user_prof', to:'users#edit_prof'
  patch '/users/:id/edit_user_prof', to:'users#update_prof'
  get 'users/:id/edit_user_account', to:'users#edit_account'
  get 'users/:id/edit_user_password', to:'users#edit_password'
  patch 'users/:id/edit_user_password', to:'users#update_password'
  get 'users/:id/withdraw', to:'users#withdraw'
  get 'announce_send_password', to:'password_resets#announce_send_password'
  get 'announce_success_change_password', to:'password_resets#announce_success_change_password'
  get 'email_resets/:id/new', to:'email_resets#new'
  post 'email_resets/:id/create', to:'email_resets#create'
  post '/email_resets/:id/update', to:'email_resets#update'
  # movie
  get 'movies/list', to:'movies#list'
  get 'movies/list/now', to:'movies#now'
  get 'movies/list/rental_coming', to:'movies#rental_coming'
  get 'movies/list/rental_now', to:'movies#rental_now'
  # get 'movies/list/recommended', to:'movies#recommended'
  get 'movies/list/year/:year', to:'movies#year' 
  get 'movies/list/genre/:genre', to:'movies#genre' 
  get 'movies/list/production/:production', to:'movies#production' 
  # drama
  get 'dramas/list', to:'dramas#list'
  get 'dramas/list/now', to:'dramas#now'
  get 'dramas/list/rental_coming', to:'dramas#rental_coming'
  get 'dramas/list/rental_now', to:'dramas#rental_now'
  #get 'dramas/list/recommended', to:'dramas#recommended'
  get 'dramas/list/year/:year', to:'dramas#year' 
  get 'dramas/list/genre/:genre', to:'dramas#genre' 
  get 'dramas/list/production/:production', to:'dramas#production' 
  # cast
  get 'casts/drama/:id', to:'casts#show_drama'
  resources :users do
    member do
      get :following, :followers, :show_review_drama, :show_book_movie, :show_book_drama
    end
  end
  resources :movies, :dramas do
    resources :reviews,           only: [:new, :create, :edit, :update]
    resources :books,             only: [:create, :destroy]
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :email_resets,        only: [:edit]
  resources :movies,              only: [:show]
  resources :dramas,              only: [:show]
  resources :casts,               only: [:show] do
    resources :likes,             only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
end

app/views/shared/_drama_genre_sidebar.html.erb
<div class="card card_top">
  <div class="card-header text-center font-weight-bold"><%=yield(:title)%></div>
</div>
<div class="row">
  <div class="col-md-4 mt-4">
    <ul class="list-group">
      <li class="list-group-item list-group-item-secondary text-center sidebar_header"><strong>ジャンルで探す</strong></li>
      <% if yield(:title) == "サスペンスのおすすめドラマ作品" %>
        <%=link_to "/dramas/list/genre/suspense", class:"list-group-item list-group-item-action bg-secondary" do%>
          サスペンス(<%=Drama.where(genre: "サスペンス").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to "/dramas/list/genre/suspense", class:"list-group-item list-group-item-action" do%>
          サスペンス(<%=Drama.where(genre: "サスペンス").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
      <% if yield(:title) == "ドキュメンタリーのおすすめドラマ作品" %>
        <%=link_to "/dramas/list/genre/documentary", class:"list-group-item list-group-item-action bg-secondary" do%>
          ドキュメンタリー(<%=Drama.where(genre: "ドキュメンタリー").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>      
      <%else%>
        <%=link_to "/dramas/list/genre/documentary", class:"list-group-item list-group-item-action" do%>
          ドキュメンタリー(<%=Drama.where(genre: "ドキュメンタリー").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>  
      <% end %>
      <% if yield(:title) == "アクションのおすすめドラマ作品" %>
        <%=link_to "/dramas/list/genre/action", class:"list-group-item list-group-item-action bg-secondary" do%>
          アクション(<%=Drama.where(genre: "アクション").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>  
      <%else%>
        <%=link_to "/dramas/list/genre/action", class:"list-group-item list-group-item-action" do%>
          アクション(<%=Drama.where(genre: "アクション").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %> 
      <% end %>
      <% if yield(:title) == "SFのおすすめドラマ作品" %>
        <%=link_to "/dramas/list/genre/SF", class:"list-group-item list-group-item-action bg-secondary" do%>
          SF(<%=Drama.where(genre: "SF").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to "/dramas/list/genre/SF", class:"list-group-item list-group-item-action" do%>
          SF(<%=Drama.where(genre: "SF").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
      <% if yield(:title) == "コメディのおすすめドラマ作品" %>
        <%=link_to "/dramas/list/genre/comedy", class:"list-group-item list-group-item-action bg-secondary" do%>
          コメディ(<%=Drama.where(genre: "コメディ").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to "/dramas/list/genre/comedy", class:"list-group-item list-group-item-action" do%>
          コメディ(<%=Drama.where(genre: "コメディ").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
      <% if yield(:title) == "ホラーのおすすめドラマ作品" %>
        <%=link_to "/dramas/list/genre/horror", class:"list-group-item list-group-item-action bg-secondary" do%>
          ホラー(<%=Drama.where(genre: "ホラー").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to "/dramas/list/genre/horror", class:"list-group-item list-group-item-action" do%>
          ホラー(<%=Drama.where(genre: "ホラー").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
    </ul>
  </div>

app/views/shared/_drama_information.html.erb
<div class="col-md-8">
  <div class="card card_top">
    <div class="card-header text-secondary">おすすめ順</div>
    <div class="card-body movie_list">
      <% @dramas.each do |drama| %>
        <div class="card mb-3">
          <div class="card-body">
            <div class="row">
              <div class="col-md-3 movie_image">
                <% if drama.picture.nil?%>
                  <%= image_tag 'no_image.jpg', size: "150x200" %>
                <%else%>
                  <%= image_tag drama.picture, size: "150x200"%>
                <% end %>
              </div>
              <div class="col-md-9 movie_text">
                <h5 class="font-weight-bold card-title"><%= drama.title%></h5>
                <p class="card-text">
                  <span class="font-weight-bold">上映日：</span><%= "#{drama.release.year}年#{drama.release.mon}月#{drama.release.day}日"%> ／
                  <span class="font-weight-bold">製作国：</span><%= link_to drama.production, "/dramas/list/production/#{drama.production_translation}"%> 
                </p>
                <p class="card-text">
                  <span class="font-weight-bold">ジャンル：</span><%= link_to drama.genre, "/dramas/list/genre/#{drama.genre_translation}"%>
                </p>
                <p class="star">
                  <span id="star-rate-<%= drama.id %>"></span>
                  <script>
                    $('#star-rate-<%= drama.id %>').raty({
                      size: 100,
                      starOff:  '<%= asset_path('star-off.png') %>',
                      starOn : '<%= asset_path('star-on.png') %>',
                      starHalf: '<%= asset_path('star-half.png') %>',
                      half: true,
                      readOnly: true,
                      score: <%= drama.reviews.average(:star).to_f %>,
                    });
                  </script> 
                </p>
                <div class="row">
                  <div class="col-md-auto">
                    <p class="mt-2"><span class="font-weight-bold">監督</span></p>
                    <% director_ids = drama.drama_casts.where(relation: "director").select(:cast_id)%>
                    <% Cast.where(id: director_ids).each do |director| %>
                      <%= link_to director.name, "/casts/drama/#{director.id}", class: "btn btn-light btn-sm cast_name" %>
                    <% end %>
                  </div>
                  <div class="col-md-auto">
                    <p class="mt-2"><span class="font-weight-bold">脚本</span></p>
                    <% writer_ids = drama.drama_casts.where(relation: "writer").select(:cast_id)%>
                    <% Cast.where(id: writer_ids).each do |writer| %>
                      <%= link_to writer.name, "/casts/drama/#{writer.id}", class: "btn btn-light btn-sm cast_name" %>
                    <% end %>
                  </div>
                </div>
                <p class="mt-2"><span class="font-weight-bold">出演者</span></p>
                <% count = 1 %>
                <% actor_ids = drama.drama_casts.where(relation: "actor").select(:cast_id)%>
                <% actor_ids.each do |actor_id| %>
                  <% if count <= 2%>
                    <% actor = Cast.find(actor_id.cast_id) %>
                    <%= link_to actor.name, "/casts/drama/#{actor.id}", class: "btn btn-light btn-sm cast_name mt-2 mr-1" %>
                  <% end %>
                  <% count += 1%>
                <% end %>
                <div class="d-block mt-2">
                <%= link_to ">>詳しい情報を見る", drama, class:"float-right cast_name"%>
                </div>
              </div>
            </div>
          </div>          
        </div>
      <% end %>
      <%= paginate @dramas, theme: 'twitter-bootstrap-4'%>
    </div>
  </div>
</div>
</div>

app/views/shared/_drama_list_sidebar.html.erb
<div class="card card_top">
  <div class="card-header text-center font-weight-bold"><%=yield(:title)%></div>
</div>
<div class="row">
  <div class="col-md-4 mt-4">
    <ul class="list-group">
      <li class="list-group-item list-group-item-secondary text-center"><strong>ドラマを探す</strong></li>
      <% if yield(:title) == "放送中のドラマ" %>
        <%=link_to dramas_list_now_path, class:"list-group-item list-group-item-action bg-secondary" do%>
          放送中のドラマ<span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to dramas_list_now_path, class:"list-group-item list-group-item-action" do%>
          放送中のドラマ<span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
      <% if yield(:title) == "レンタル開始予定のドラマ" %>
        <%=link_to dramas_list_rental_coming_path, class:"list-group-item list-group-item-action bg-secondary" do%>
          レンタル開始予定のドラマ<span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to dramas_list_rental_coming_path, class:"list-group-item list-group-item-action" do%>
          レンタル開始予定のドラマ<span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
      <% if yield(:title) == "レンタル" %>
        <%=link_to dramas_list_rental_now_path, class:"list-group-item list-group-item-action bg-secondary" do%>
          レンタル<span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to dramas_list_rental_now_path, class:"list-group-item list-group-item-action" do%>
          レンタル<span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
      <% if yield(:title) == "今話題のおすすめドラマ" %>
        <%=link_to "#", class:"list-group-item list-group-item-action bg-secondary" do%>
          今話題のおすすめドラマ<span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to "#", class:"list-group-item list-group-item-action" do%>
          今話題のおすすめドラマ<span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
      <%=link_to "/dramas/list/year/2019", class:"list-group-item list-group-item-action" do%>
        製作年（年代）<span class="float-right text-secondary">＞</span> 
      <% end %>
      <%=link_to "/dramas/list/production/america", class:"list-group-item list-group-item-action" do%>
        製作国<span class="float-right text-secondary">＞</span> 
      <% end %>
      <%=link_to "/dramas/list/genre/suspense", class:"list-group-item list-group-item-action" do%>
        ジャンル<span class="float-right text-secondary">＞</span> 
      <% end %>
    </ul>
  </div>

app/views/shared/_drama_production_sidebar.html.erb
<div class="card card_top">
  <div class="card-header text-center font-weight-bold"><%=yield(:title)%></div>
</div>
<div class="row">
  <div class="col-md-4 mt-4">
    <ul class="list-group">
      <li class="list-group-item list-group-item-secondary text-center sidebar_header"><strong>製作国で探す</strong></li>
      <% if yield(:title) == "アメリカのおすすめドラマ作品" %>
        <%=link_to "/dramas/list/production/america", class:"list-group-item list-group-item-action bg-secondary" do%>
          アメリカ(<%=Drama.where(production: "アメリカ").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to "/dramas/list/production/america", class:"list-group-item list-group-item-action" do%>
          アメリカ(<%=Drama.where(production: "アメリカ").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
      <% if yield(:title) == "イギリスのおすすめドラマ作品" %>
        <%=link_to "/dramas/list/production/england", class:"list-group-item list-group-item-action bg-secondary" do%>
          イギリス(<%=Drama.where(production: "イギリス").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>      
      <%else%>
        <%=link_to "/dramas/list/production/england", class:"list-group-item list-group-item-action" do%>
          イギリス(<%=Drama.where(production: "イギリス").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>  
      <% end %>
      <% if yield(:title) == "スペインのおすすめドラマ作品" %>
        <%=link_to "/dramas/list/production/spain", class:"list-group-item list-group-item-action bg-secondary" do%>
          スペイン(<%=Drama.where(production: "スペイン").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>  
      <%else%>
        <%=link_to "/dramas/list/production/spain", class:"list-group-item list-group-item-action" do%>
          スペイン(<%=Drama.where(production: "スペイン").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %> 
      <% end %>
      <% if yield(:title) == "シリアのおすすめドラマ作品" %>
        <%=link_to "/dramas/list/production/syria", class:"list-group-item list-group-item-action bg-secondary" do%>
          シリア(<%=Drama.where(production: "シリア").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to "/dramas/list/production/syria", class:"list-group-item list-group-item-action" do%>
          シリア(<%=Drama.where(production: "シリア").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
      <% if yield(:title) == "カナダのおすすめドラマ作品" %>
        <%=link_to "/dramas/list/production/canada", class:"list-group-item list-group-item-action bg-secondary" do%>
          カナダ(<%=Drama.where(production: "カナダ").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to "/dramas/list/production/canada", class:"list-group-item list-group-item-action" do%>
          カナダ(<%=Drama.where(production: "カナダ").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
            <% if yield(:title) == "フランスのおすすめドラマ作品" %>
        <%=link_to "/dramas/list/production/france", class:"list-group-item list-group-item-action bg-secondary" do%>
          フランス(<%=Drama.where(production: "フランス").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to "/dramas/list/production/france", class:"list-group-item list-group-item-action" do%>
          フランス(<%=Drama.where(production: "フランス").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
    </ul>
  </div>

app/views/shared/_edit_user_sidebar.html.erb
<div class="card card_top">
  <div class="card-header text-center font-weight-bold"><%=yield(:title)%></div>
</div>
<div class="row">
  <div class="col-md-4 mt-4">
    <ul class="list-group">
      <li class="list-group-item list-group-item-secondary text-center sidebar_header"><strong>設定</strong></li>
      <% if yield(:title) == "プロフィール編集" %>
        <%=link_to "/users/#{@user.id}/edit_user_prof", class:"list-group-item list-group-item-action bg-secondary" do%>
          プロフィール編集<span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%> 
        <%=link_to "/users/#{@user.id}/edit_user_prof", class:"list-group-item list-group-item-action" do%>
          プロフィール編集<span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
      <% if yield(:title) == "アカウント情報" || yield(:title) == "メール設定" || yield(:title) == "パスワード設定" || yield(:title) == "退会"%>
        <%=link_to "/users/#{@user.id}/edit_user_account", class:"list-group-item list-group-item-action bg-secondary" do%>
          アカウント情報<span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to "/users/#{@user.id}/edit_user_account", class:"list-group-item list-group-item-action" do%>
          アカウント情報<span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
      <% if yield(:title) == "ブロックしたユーザー" %>
        <%=link_to '#', class:"list-group-item list-group-item-action bg-secondary" do%>
          ブロックしたユーザー<span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to '#', class:"list-group-item list-group-item-action" do%>
          ブロックしたユーザー<span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
      <li class="list-group-item list-group-item-secondary text-center sidebar_header"><strong>Kamarksについて</strong></li>
      <%=link_to about_path, class:"list-group-item list-group-item-action" do%>
        Kamarksの使い方<span class="float-right text-secondary">＞</span> 
      <% end %>
      <%=link_to help_path, class:"list-group-item list-group-item-action" do%>
        ヘルプ<span class="float-right text-secondary">＞</span> 
      <% end %>
      <%=link_to '#', class:"list-group-item list-group-item-action" do%>
        利用規約<span class="float-right text-secondary">＞</span> 
      <% end %>
      <%=link_to '#', class:"list-group-item list-group-item-action" do%>
        プライバシーポリシー<span class="float-right text-secondary">＞</span> 
      <% end %>
    </ul>
  </div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any?%>
  <div id="error_explanation">
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/shared/_movie_genre_sidebar.html.erb
<div class="card card_top">
  <div class="card-header text-center font-weight-bold"><%=yield(:title)%></div>
</div>
<div class="row">
  <div class="col-md-4 mt-4">
    <ul class="list-group">
      <li class="list-group-item list-group-item-secondary text-center sidebar_header"><strong>ジャンルで探す</strong></li>
      <% if yield(:title) == "サスペンスのおすすめ映画作品" %>
        <%=link_to "/movies/list/genre/suspense", class:"list-group-item list-group-item-action bg-secondary" do%>
          サスペンス(<%=Movie.where(genre: "サスペンス").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to "/movies/list/genre/suspense", class:"list-group-item list-group-item-action" do%>
          サスペンス(<%=Movie.where(genre: "サスペンス").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
      <% if yield(:title) == "ドキュメンタリーのおすすめ映画作品" %>
        <%=link_to "/movies/list/genre/documentary", class:"list-group-item list-group-item-action bg-secondary" do%>
          ドキュメンタリー(<%=Movie.where(genre: "ドキュメンタリー").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>      
      <%else%>
        <%=link_to "/movies/list/genre/documentary", class:"list-group-item list-group-item-action" do%>
          ドキュメンタリー(<%=Movie.where(genre: "ドキュメンタリー").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>  
      <% end %>
      <% if yield(:title) == "アクションのおすすめ映画作品" %>
        <%=link_to "/movies/list/genre/action", class:"list-group-item list-group-item-action bg-secondary" do%>
          アクション(<%=Movie.where(genre: "アクション").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>  
      <%else%>
        <%=link_to "/movies/list/genre/action", class:"list-group-item list-group-item-action" do%>
          アクション(<%=Movie.where(genre: "アクション").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %> 
      <% end %>
      <% if yield(:title) == "SFのおすすめ映画作品" %>
        <%=link_to "/movies/list/genre/SF", class:"list-group-item list-group-item-action bg-secondary" do%>
          SF(<%=Movie.where(genre: "SF").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to "/movies/list/genre/SF", class:"list-group-item list-group-item-action" do%>
          SF(<%=Movie.where(genre: "SF").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
      <% if yield(:title) == "コメディのおすすめ映画作品" %>
        <%=link_to "/movies/list/genre/comedy", class:"list-group-item list-group-item-action bg-secondary" do%>
          コメディ(<%=Movie.where(genre: "コメディ").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to "/movies/list/genre/comedy", class:"list-group-item list-group-item-action" do%>
          コメディ(<%=Movie.where(genre: "コメディ").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
      <% if yield(:title) == "ホラーのおすすめ映画作品" %>
        <%=link_to "/movies/list/genre/horror", class:"list-group-item list-group-item-action bg-secondary" do%>
          ホラー(<%=Movie.where(genre: "ホラー").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to "/movies/list/genre/horror", class:"list-group-item list-group-item-action" do%>
          ホラー(<%=Movie.where(genre: "ホラー").count %> 件) <span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
    </ul>
  </div>

app/views/shared/_movie_list_sidebar.html.erb
<div class="card card_top">
  <div class="card-header text-center font-weight-bold"><%=yield(:title)%></div>
</div>
<div class="row">
  <div class="col-md-4 mt-4">
    <ul class="list-group">
      <li class="list-group-item list-group-item-secondary text-center"><strong>映画を探す</strong></li>
      <% if yield(:title) == "上映中の映画" %>
        <%=link_to movies_list_now_path, class:"list-group-item list-group-item-action bg-secondary" do%>
          上映中の映画<span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to movies_list_now_path, class:"list-group-item list-group-item-action" do%>
          上映中の映画<span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
      <% if yield(:title) == "レンタル開始予定の映画" %>
        <%=link_to movies_list_rental_coming_path, class:"list-group-item list-group-item-action bg-secondary" do%>
          レンタル開始予定の映画<span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to movies_list_rental_coming_path, class:"list-group-item list-group-item-action" do%>
          レンタル開始予定の映画<span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
      <% if yield(:title) == "レンタル" %>
        <%=link_to movies_list_rental_now_path, class:"list-group-item list-group-item-action bg-secondary" do%>
          レンタル<span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to movies_list_rental_now_path, class:"list-group-item list-group-item-action" do%>
          レンタル<span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
      <% if yield(:title) == "今話題のおすすめ映画" %>
        <%=link_to "#", class:"list-group-item list-group-item-action bg-secondary" do%>
          今話題のおすすめ映画<span class="float-right text-secondary">＞</span> 
        <% end %>
      <%else%>
        <%=link_to "#", class:"list-group-item list-group-item-action" do%>
          今話題のおすすめ映画<span class="float-right text-secondary">＞</span> 
        <% end %>
      <% end %>
      <%=link_to "/movies/list/year/2019", class:"list-group-item list-group-item-action" do%>
        製作年（年代）<span class="float-right text-secondary">＞</span> 
      <% end %>
      <%=link_to "/movies/list/production/america", class:"list-group-item list-group-item-action" do%>
        製作国<span class="float-right text-secondary">＞</span> 
      <% end %>
      <%=link_to "/movies/list/genre/suspense", class:"list-group-item list-group-item-action" do%>
        ジャンル<span class="float-right text-secondary">＞</span> 
      <% end %>
    </ul>
  </div>